version: '3.7'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn hello_docker.wsgi:application --bind 0.0.0.0:8000
    volumes: 
      - static_volume:/usr/src/app/hello_docker/staticfiles
      - media_volume:/usr/src/app/hello_docker/mediafiles
    expose: 
      - 8000
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:11.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env.db
  nginx:
    build: ./nginx
    volumes: 
      - static_volume:/usr/src/app/hello_docker/staticfiles
      - media_volume:/usr/src/app/hello_docker/mediafiles
    ports: 
      - 1337:80
    depends_on: 
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: